[versions]
kotlin = "2.4.10"
springBoot = "4.1.1"
springDependencyMgmt = "1.1.7"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-mgmt = { id = "io.spring.dependency-management", version.ref = "springDependencyMgmt" }
